export const USER_ROLES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  HOSPITAL_MANAGER: "HOSPITAL_MANAGER",
  VIRTUAL_CARE_COORDINATOR: "VIRTUAL_CARE_COORDINATOR",
  CLINICIAN: "CLINICIAN",
  CHP: "CHP",
  HEALTH_RECORDS_OFFICER: "HEALTH_RECORDS_OFFICER",
  PHARMACIST: "PHARMACIST",
  RESEARCH_ME_OFFICER: "RESEARCH_ME_OFFICER",
} as const;

export const QUEUE_STATUSES = {
  WAITING: "WAITING",
  ASSIGNED: "ASSIGNED",
  IN_CONSULTATION: "IN_CONSULTATION",
  COMPLETED: "COMPLETED",
  REFERRED: "REFERRED",
  NOT_REACHED: "NOT_REACHED",
  CANCELLED: "CANCELLED",
} as const;

export const PATIENT_STATUSES = {
  PRE_ENROLLED: "PRE_ENROLLED",
  AWAITING_TAIFACARE_REGISTRATION: "AWAITING_TAIFACARE_REGISTRATION",
  TAIFACARE_LINKED: "TAIFACARE_LINKED",
  ACTIVE_VIRTUAL_CARE: "ACTIVE_VIRTUAL_CARE",
  INACTIVE: "INACTIVE",
  LOST_TO_FOLLOW_UP: "LOST_TO_FOLLOW_UP",
  EXITED_DECEASED: "EXITED_DECEASED",
} as const;